on: push
name: Build and deploy on push
jobs:
  build:
    name: shalzz/zola-deploy-action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@@v3.0.0
    - name: shalzz/zola-deploy-action
      uses: shalzz/zola-deploy-action@v0.16.1-1
      env:
        PAGES_BRANCH: gh-pages
        BUILD_DIR: .
        BUILD_FLAGS: --drafts
        GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
