on: push
name: Build and deploy on push

permissions:
  contents: write

jobs:
  build:
    name: shalzz/zola-deploy-action
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v4
      - name: Build and deploy
        uses: shalzz/zola-deploy-action@v0.21.0
        env:
          PAGES_BRANCH: gh-pages
          BUILD_DIR: .
          BUILD_FLAGS: ""
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
